# permissions for end users to edit presentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presentation-editor-role
rules:
- apiGroups:
  - dataminded.be
  resources:
  - presentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataminded.be
  resources:
  - presentations/status
  verbs:
  - get
